export const fakeData = [
    {
      id: 1,
      firstName: 'Kashinath',
      lastName: 'C',
      wageRate: 650,
      noOfDayswork: 27,
      overtimeHrs:0,
      basicWage:419,
      specialBasic:0,
      wageDA:0,      
      paymentovertime:0,
      HRA:21,
      otherSpecialAllows:260, 
      deductSociety:0,
      deductPT:200,
      deductInsurance:0,
      deductOthers:0,
      deductRecoveries:0,
      TransactionId:0,
      dateOfPayment:0,
      remarkOfPayment:"remark ok"
    },
    {
      id: 2,
      firstName: 'Ajay',
      lastName: 'Yeole',
      wageRate: 700,
      noOfDayswork: 27,
      overtimeHrs:0,
      basicWage:419,
      specialBasic:0,
      wageDA:0,      
      paymentovertime:0,
      HRA:21,
      otherSpecialAllows:260, 
      deductSociety:0,
      deductPT:200,
      deductInsurance:0,
      deductOthers:0,
      deductRecoveries:0,
      TransactionId:0,
      dateOfPayment:0,
      remarkOfPayment:"remark ok"
    },
    {
      id: 3,
      firstName: 'Ashish',
      lastName: 'W',
      wageRate: 775,
      noOfDayswork: 27,
      overtimeHrs:0,
      basicWage:419,
      specialBasic:0,
      wageDA:0,      
      paymentovertime:0,
      HRA:21,
      otherSpecialAllows:335,  
      deductSociety:0,
      deductPT:200,
      deductInsurance:0,
      deductOthers:0,
      deductRecoveries:0,      
      TransactionId:0,
      dateOfPayment:0,
      remarkOfPayment:"775 ok"
    },
    {
      id: 4,
      firstName: 'Angad',
      lastName: 'M',
      wageRate: 500,
      noOfDayswork: 16,
      overtimeHrs:0,
      basicWage:381,
      specialBasic:0,
      wageDA:0,      
      paymentovertime:0,
      HRA:19,
      otherSpecialAllows:100, 
      deductSociety:0,
      deductPT:200,
      deductInsurance:0,
      deductOthers:0,
      deductRecoveries:0,      
      TransactionId:0,
      dateOfPayment:0,
      remarkOfPayment:"remark ok"
    }   
  ];