export const fakeData = [
    {
      id: '9s41rp',
      firstName: 'Kelvin',
      lastName: 'Langosh',
      wageRate: 650,
      noOfDayswork: 25,
      overtimeHrs:0,
      basicWage:419,
      specialBasic:0,
      wageDA:0,
      totalWage:11313,
      paymentovertime:0,
      HRA:21,
      otherSpecialAllows:260,
      grandTotal:17549,
      deductPf:1358,
      deductESIC:132,
      deductSociety:0,
      deductPT:200,
      deductInsurance:0,
      deductOthers:0,
      deductRecoveries:0,
      totalDeduction:1690,
      netPayment:15859,
      pfEmployer:1488,
      TransactionId:0,
      dateOfPayment:0,
      remarkOfPayment:"remark ok"

    },
    {
      id: '08m6rx',
      firstName: 'Molly',
      lastName: 'Purdy',
      wageRate: 650,
      noOfDayswork: 25,
      overtimeHrs:0,
      basicWage:419,
      specialBasic:0,
      wageDA:0,
      totalWage:11313,
      paymentovertime:0,
      HRA:21,
      otherSpecialAllows:260,
      grandTotal:17549,
      deductPf:1358,
      deductESIC:132,
      deductSociety:0,
      deductPT:200,
      deductInsurance:0,
      deductOthers:0,
      deductRecoveries:0,
      totalDeduction:1690,
      netPayment:15859,
      pfEmployer:1488,
      TransactionId:0,
      dateOfPayment:0,
      remarkOfPayment:"remark ok"
    },
    {
        id: '08m6rx',
        firstName: 'Molly',
        lastName: 'Purdy',
        wageRate: 650,
        noOfDayswork: 25,
        overtimeHrs:0,
        basicWage:419,
        specialBasic:0,
        wageDA:0,
        totalWage:11313,
        paymentovertime:0,
        HRA:21,
        otherSpecialAllows:260,
        grandTotal:17549,
        deductPf:1358,
        deductESIC:132,
        deductSociety:0,
        deductPT:200,
        deductInsurance:0,
        deductOthers:0,
        deductRecoveries:0,
        totalDeduction:1690,
        netPayment:15859,
        pfEmployer:1488,
        TransactionId:0,
        dateOfPayment:0,
        remarkOfPayment:"remark ok"
      },
      {
        id: '08m6rx',
        firstName: 'Molly',
        lastName: 'Purdy',
        wageRate: 650,
        noOfDayswork: 25,
        overtimeHrs:0,
        basicWage:419,
        specialBasic:0,
        wageDA:0,
        totalWage:11313,
        paymentovertime:0,
        HRA:21,
        otherSpecialAllows:260,
        grandTotal:17549,
        deductPf:1358,
        deductESIC:132,
        deductSociety:0,
        deductPT:200,
        deductInsurance:0,
        deductOthers:0,
        deductRecoveries:0,
        totalDeduction:1690,
        netPayment:15859,
        pfEmployer:1488,
        TransactionId:0,
        dateOfPayment:0,
        remarkOfPayment:"remark ok"
      },    
  ];
  
  //50 us states array
  export const usStates = [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
    'Puerto Rico',
  ];